### ISSUE TITLE
Can't import an own module

### ISSUE THREAD

**Issue by zhoukekestar** [mkloubert/vs-script-commands#7]
```js
    // import an own module
    var myModule = require('./myModule');
```

I have [replace.js](https://github.com/zhoukekestar/vscode-commands/blob/master/src/replace.js) & import [replace-davinci](https://github.com/zhoukekestar/vscode-commands/blob/master/src/replace-davinci.js).

It should output `replace davinci` in `replace-davinci.js` but can't find anything.
If i want to use `replaceDavinci.replace(text, fileName);`, it occur  `replace is undefined`.

I love this extension and Google it for a long time. Hope you can help me to fixed it. Thanks a lot.

**Comment by mkloubert** [comment]
@zhoukekestar 

It seams that the `replace()` function in your [replace-davinci.js](https://github.com/zhoukekestar/vscode-commands/blob/master/src/replace-davinci.js) file is commented out.

The module is found, but no function with that name seems to be exported.

**Comment by zhoukekestar** [comment]
Sorry for that code confused you. I try it again and found the reason that `vs-script-command` will hot-reload the js file which is defined in `settings.json` but will cache the js file which is required by command-js-file. I have to reload VSCode window to load latest js file so that i got that issue `something is undefined`.
So the issue is fixed. But i thought that the best way is to hot-reload all js files. Thanks anyway for your awesome extension~. 😃

**Comment by tomzx** [comment]
Any particular reason the `required` files are not hot-reloaded? It seems that it would be easier to develop scripts if you could make use of other modules without having to force a reload every time you make a change to a `required` module.

**Comment by jacobweber** [comment]
Even after closing and reopening vscode, any custom module that I `require` returns an empty object, with nothing exported. Not sure how to work around this.
